### ISSUE TITLE
Change jumper to program?

### ISSUE THREAD

**Issue by jpmeijers** [jcaridadhdez/RAK811-tracker#2]
I'm unsure about programming the board as I still can't get it to work on my Ubuntu computer.

Is it necessary to change the jump in the corner of the board as is shown in the photos here:
http://support.rakwireless.com/topic/183/rak811-tracker-howto/28

**Comment by jcaridadhdez** [comment]
It is necessary to change the jumper to the program position (joining the 1st and 2nd positions) before power the board, program it and then power off the board, change back the jumper and power to boot normally.

A wiki page will be written to explain this.

**Comment by jpmeijers** [comment]
Removing and repowering the board is not necessary. You can also press the reset button.

**Comment by jcaridadhdez** [comment]
for sure!
